name: cat_dog_classifier
description: A project to classify cats and dogs.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.2
  tflite: ^1.1.2
  splashscreen: ^1.3.5
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/cat_dog_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
